# Generated by Django 3.1 on 2020-09-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'waiting'), (1, 'processing'), (2, 'done')], default=0, verbose_name='status'),
        ),
    ]
