# Generated by Django 3.1 on 2020-09-30 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['order_date']},
        ),
        migrations.AlterField(
            model_name='customer',
            name='addres',
            field=models.CharField(blank=True, help_text='Use as default delivery addres.', max_length=255, null=True, verbose_name='addres'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True, verbose_name='order date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'waiting'), (1, 'processing'), (2, 'done'), (3, 'canceled')], default=0, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='cart_items',
            field=models.ManyToManyField(through='shop.Cart', to='shop.Item'),
        ),
    ]
